var skills = {
    "Cleave": "Deals light Slash damage to one foe.",
    "Power Slash": "Deals light Slash damage to one foe.",
    "Zan-ei": "Deals medium Slash damage to one foe. (\"New Moon\" bonus)",
    "Getsu-ei": "Deals medium Slash damage to one foe. (\"Full Moon\" bonus)",
    "Gale Slash": "Deals medium Slash damage to all foes.",
    "Mighty Swing": "Deals medium Slash damage to one foe.",
    "Fatal End": "Deals medium Slash damage to one foe.",
    "Blade of Fury": "Deals medium Slash damage to all foes. (1-3 hits)",
    "Deathbound": "Deals heavy Slash damage to all foes.",
    "Tempest Slash": "Deals heavy Slash damage to one foe. (1-2 hits)",
    "Heaven's Blade": "Deals severe Slash damage to one foe.Michael exclusive.",
    "Brave Blade": "Deals severe Slash damage to one foe.",
    "Vorpal Blade": "Deals heavy Slash damage to all foes. (1.5x \"Great\" condition bonus)",
    "Bash": "Deals light Strike damage to one foe.",
    "Sonic Punch": "Deals light Strike damage to one foe.",
    "Assault Dive": "Deals light Strike damage to one foe.",
    "Kill Rush": "Deals light Strike damage to one foe. (1-2 hits)",
    "Swift Strike": "Deals light Strike damage to all foes. (1-3 hits)",
    "Herculean Strike": "Deals medium Strike damage to all foes.",
    "Gigantic Fist": "Deals heavy Strike damage to one foe.",
    "Heat Wave": "Deals medium Strike damage to all foes.",
    "Vicious Strike": "Deals heavy Strike damage to all foes. ",
    "Weary Thrust": "Deals heavy Strike damage to one foe. (1.5x \"Tired\" condition bonus)",
    "Akasha Arts": "Deals heavy Strike damage 1x to 2x to all foes. ",
    "God's Hand": "Deals severe Strike damage to one foe. ",
    "Single Shot": "Deals light Pierce damage to one foe.",
    "Double Fangs": "Deals light Pierce damage to one foe. (2 hits)",
    "Holy Arrow": "Deals light Pierce damage / Charms one foe. (25% chance)",
    "Twin Shot": "Deals medium Pierce damage to one foe. (2 hits)",
    "Torrent Shot": "Deals light Pierce damage to one foe. (2-3 hits)",
    "Cruel Attack": "Deals medium Pierce damage to one foe. (1.5x to Downed foes)",
    "Poison Arrow": "Deals heavy Pierce damage / Poisons one foe. (25% chance)",
    "Vile Assault": "Deals heavy Pierce damage to one foe. (1.5x to Downed foes)",
    "Arrow Rain": "Deals medium Pierce damage to all foes. (1-2 hits)",
    "Myriad Arrows": "Deals medium Pierce damage to all foes. (1-2 hits)",
    "Primal Force": "Deals severe Pierce damage to one foe.",
    "Pralaya": "Deals severe Pierce damage / instills Fear in all foes. (25% chance)Shiva exclusive.",
    "Agi": "Deals light Fire damage to one foe.",
    "Maragi": "Deals light Fire damage to all foes.",
    "Agilao": "Deals medium Fire damage to one foe.",
    "Maragion": "Deals medium Fire damage to all foes.",
    "Agidyne": "Deals heavy Fire damage to one foe.",
    "Maragidyne": "Deals heavy Fire damage to all foes.",
    "Ragnarok": "Deals severe Fire damage to one foe.Surt exclusive.",
    "Maralagidyne": "Deals severe Fire damage to all foes.Mara exclusive.",
    "Bufu": "Deals light Ice damage / Freezes one foe. (10% chance)",
    "Mabufu": "Deals light Ice damage / Freezes all foes. (8% chance)",
    "Bufula": "Deals medium Ice damage / Freezes one foe. (10% chance)",
    "Mabufula": "Deals medium Ice damage / Freezes all foes. (8% chance)",
    "Bufudyne": "Deals heavy Ice damage / Freezes one foe. (10% chance)",
    "Mabufudyne": "Deals heavy Ice damage / Freezes all foes. (8% chance)",
    "Niflheim": "Deals severe Ice damage / Freezes one foe. (100% chance)Skadi exclusive.",
    "Zio": "Deals light Elec damage / Shocks one foe. (10% chance)",
    "Mazio": "Deals light Elec damage / Shocks all foes. (8% chance)",
    "Zionga": "Deals medium Elec damage / Shocks one foe. (10% chance)",
    "Mazionga": "Deals medium Elec damage / Shocks all foes. (8% chance)",
    "Ziodyne": "Deals heavy Elec damage / Shocks one foe. (10% chance)",
    "Maziodyne": "Deals heavy Elec damage / Shocks all foes. (8% chance)",
    "Thunder Reign": "Deals severe Elec damage / Shocks one foe. (100% chance)Odin exclusive.",
    "Garu": "Deals light Wind damage to one foe.",
    "Magaru": "Deals light Wind damage to all foes.",
    "Garula": "Deals medium Wind damage to one foe.",
    "Magarula": "Deals medium Wind damage to all foes.",
    "Garudyne": "Deals heavy Wind damage to one foe.",
    "Magarudyne": "Deals heavy Wind damage to all foes.",
    "Panta Rhei": "Deals severe Wind damage to one foe.Norn exclusive.",
    "Hama": "Light: instant kill, 1 foe. (25% chance)",
    "Mahama": "Light: instant kill, all foes. (20% chance)",
    "Hamaon": "Light: instant kill, 1 foe (high odds). (50% chance)",
    "Mahamaon": "Light: instant kill, all foes (high odds). (40% chance)",
    "Samsara": "Light: instant kill, all foes (very high). (80% chance)Daisoujou exclusive.",
    "Mudo": "Darkness: instant kill, 1 foe. (25% chance)",
    "Mamudo": "Darkness: instant kill, all foes. (20% chance)",
    "Mudoon": "Darkness: instant kill, 1 foe (high odds). (50% chance)",
    "Mamudoon": "Darkness: instant kill, all foes (high odds). (40% chance)",
    "Die for Me!": "Darkness: instant kill, all foes (very high). (80% chance)Alice exclusive.",
    "Dia": "Slightly restores 1 ally's HP.",
    "Media": "Slightly restores party's HP.",
    "Diarama": "Moderately restores 1 ally's HP. ",
    "Mediarama": "Moderately restores party's HP.",
    "Diarahan": "Fully restores 1 ally's HP.",
    "Mediarahan": "Fully restores party's HP.",
    "Salvation": "Fully restores party's HP. Cures ailments.",
    "Recarm": "Revives an ally, restoring 50% of HP.",
    "Samarecarm": "Revives an ally, fully restoring HP.",
    "Patra": "Dispels Panic, Fear, and Distress (1 ally).",
    "Re Patra": "Assists 1 ally who's been Knocked Down.",
    "Posumudi": "Neutralizes Poison (1 ally).",
    "Charmdi": "Dispels Charm (1 ally).",
    "Enradi": "Dispels Rage (1 ally).",
    "Me Patra": "Dispels Panic, Fear, and Distress (party).",
    "Amrita": "Cures all ailments (party).",
    "Tarukaja": "Increases 1 ally's Attack.",
    "Tarunda": "Decreases 1 foe's Attack.",
    "Matarukaja": "Increases party's Attack.",
    "Matarunda": "Decreases all foe's Attack.",
    "Rakukaja": "Increases 1 ally's Defense.",
    "Rakunda": "Decreases 1 foe's Defense.",
    "Marakukaja": "Increases party's Defense.",
    "Marakunda": "Decreases all foe's Defense.",
    "Sukukaja": "Increases 1 ally's Hit/Evasion rate.",
    "Sukunda": "Decreases 1 foe's Hit/Evasion rate.",
    "Masukukaja": "Increases party's Hit/Evasion rate.",
    "Masukunda": "Decreases all foe's Hit/Evasion rate.",
    "Dekunda": "Nullifies stat penalties on party.",
    "Dekaja": "Nullifies stat bonuses on all foes.",
    "Rebellion": "Increases Critical Rate (all).",
    "Revolution": "Greatly increases Critical Rate (all).",
    "Power Charge": "Doubles physical damage dealt next turn. (2.5x damage)",
    "Mind Charge": "Doubles magic damage dealt next turn. (2.5x damage)",
    "Fire Break": "Reduces 1 foe's Fire resistance to average.",
    "Ice Break": "Reduces 1 foe's Ice resistance to average.",
    "Elec Break": "Reduces 1 foe's Electricity resistance to average.",
    "Wind Break": "Reduces 1 foe's Wind resistance to average.",
    "Tetrakarn": "Barrier that reflects physical damage 1x per ally.",
    "Makarakarn": "Barrier that reflects magic damage 1x per ally.",
    "Evil Touch": "Instills Fear in 1 foe. (25% chance)",
    "Evil Smile ": "Instills Fear in all foes. (25% chance)",
    "Ghastly Wail": "Instantly kills all foes who are fearful.",
    "Pulinpa": "Makes 1 foe Panic. (25% chance)",
    "Tentarafoo ": "Makes all foes Panic. (25% chance)",
    "Bewilder": "Distresses 1 foe. (25% chance)",
    "Eerie Sound ": "Distresses all foes. (25% chance)",
    "Poisma": "Poisons 1 foe. (25% chance)",
    "Poison Mist": "Poisons all foes. (25% chance)",
    "Virus Breath": "Deals damage / Poisons all foes. (25% of HP / 25% chance)",
    "Marin Karin": "Charms 1 foe. (25% chance)",
    "Sexy Dance": "Charms all foes. (25% chance)",
    "Provoke": "Enrages 1 foe. (25% chance)",
    "Infuriate": "Enrages all foes. (25% chance)",
    "Recarmdra": "User's HP becomes 1; Allies' HP restored.",
    "Trafuri": "Enables escape from most battles.",
    "Life Drain": "Drains 35 HP from one foe.",
    "Spirit Drain": "Drains 20 SP from one foe.",
    "Foul Breath": "Doubles ailment susceptibility to one foe for three turns.",
    "Stagnant Air": "Doubles ailment susceptibility to everyone for three turns.",
    "Megido": "Deals medium Almighty damage to all foes.",
    "Megidola": "Deals heavy Almighty damage to all foes.",
    "Megidolaon ": "Deals severe Almighty damage to all foes.",
    "Black Viper": "Deals massive Almighty damage to one foe.Satan exclusive.",
    "Morning Star": "Deals massive Almighty damage to all foes.Helel exclusive.",
    "Dodge Slash": "Evasion rate doubled vs Slash attacks.",
    "Evade Slash": "Evasion rate tripled vs Slash attacks.",
    "Resist Slash": "Reduces damage from Slash attacks.",
    "Null Slash": "Nullifies damage from Slash attacks.",
    "Repel Slash": "Reflects damage from Slash attacks.",
    "Absorb Slash": "Drains damage from Slash attacks.",
    "Dodge Strike": "Evasion rate doubled vs Strike attacks.",
    "Evade Strike": "Evasion rate tripled vs Strike attacks.",
    "Resist Strike": "Reduces damage from Strike attacks.",
    "Null Strike": "Nullifies damage from Strike attacks.",
    "Repel Strike": "Reflects damage from Strike attacks.",
    "Absorb Strike": "Drains damage from Strike attacks.",
    "Dodge Pierce": "Evasion rate doubled vs Pierce attacks.",
    "Evade Pierce": "Evasion rate tripled vs Pierce attacks.",
    "Resist Pierce": "Reduces damage from Pierce attacks.",
    "Null Pierce": "Nullifies damage from Pierce attacks.",
    "Repel Pierce": "Reflects damage from Pierce attacks.",
    "Absorb Pierce": "Drains damage from Pierce attacks.",
    "Dodge Fire": "Evasion rate doubled vs Fire attacks.",
    "Evade Fire": "Evasion rate tripled vs Fire attacks.",
    "Resist Fire": "Reduces damage from Fire attacks.",
    "Null Fire": "Nullifies damage from Fire attacks.",
    "Repel Fire": "Reflects damage from Fire attacks.",
    "Absorb Fire": "Drains damage from Fire attacks.",
    "Dodge Ice": "Evasion rate doubled vs Ice attacks.",
    "Evade Ice": "Evasion rate tripled vs Ice attacks.",
    "Resist Ice": "Reduces damage from Ice attacks.",
    "Null Ice": "Nullifies damage from Ice attacks.",
    "Repel Ice": "Reflects damage from Ice attacks.",
    "Absorb Ice": "Drains damage from Ice attacks.",
    "Dodge Elec": "Evasion rate doubled vs Elec attacks.",
    "Evade Elec": "Evasion rate tripled vs Elec attacks.",
    "Resist Elec": "Reduces damage from Elec attacks.",
    "Null Elec": "Nullifies damage from Elec attacks.",
    "Repel Elec": "Reflects damage from Elec attacks.",
    "Absorb Elec": "Drains damage from Elec attacks.",
    "Dodge Wind": "Evasion rate doubled vs Wind attacks.",
    "Evade Wind": "Evasion rate tripled vs Wind attacks.",
    "Resist Wind": "Reduces damage from Wind attacks.",
    "Null Wind": "Nullifies damage from Wind attacks.",
    "Repel Wind": "Reflects damage from Wind attacks.",
    "Absorb Wind": "Drains damage from Wind attacks.",
    "Survive Light": "Low odds of revival vs Light magic. (50% chance, revive with 1 HP)",
    "Endure Light": "Automatic revival vs Light magic. (Revive with 1 HP)",
    "Resist Light": "Halves chance of death via a Light attack.",
    "Null Light": "Nullifies Light attacks.",
    "Repel Light": "Reflects Light attacks.",
    "Survive Dark": "Low odds of revival vs Darkness magic. (50% chance, revive with 1 HP)",
    "Endure Dark": "Automatic revival vs Darkness magic. (Revive with 1 HP)",
    "Resist Dark": "Halves chance of death via a Darkness attack.",
    "Null Dark": "Nullifies Darkness attacks.",
    "Repel Dark": "Reflects Darkness attacks.",
    "Fire Boost": "Strengthens Fire attacks by 25%.",
    "Fire Amp": "Greatly strengthens Fire attacks by 50%.",
    "Ice Boost": "Strengthens Ice attacks by 25%.",
    "Ice Amp": "Greatly strengthens Ice attacks by 50%.",
    "Elec Boost": "Strengthens Electricity attacks by 25%.",
    "Elec Amp": "Greatly strengthens Elec attacks by 50%.",
    "Wind Boost": "Strengthens Wind attacks by 25%.",
    "Wind Amp": "Greatly strengthens Wind attacks by 50%.",
    "Hama Boost": "Increases success rate of Light magic by 50%.",
    "Mudo Boost": "Increases success rate of Darkness magic by 50%.",
    "Fear Boost": "Increases odds of instilling Fear by 50%.",
    "Panic Boost": "Increases odds of instilling Panic by 50%.",
    "Distress Boost": "Increases odds of Distressing a foe by 50%",
    "Poison Boost": "Increases odds of Poisoning a foe by 50%.",
    "Charm Boost": "Increases odds of Charming a foe by 50%.",
    "Rage Boost": "Increases odds of Enraging a foe by 50%.",
    "Ailment Boost": "Increases odds of inflicting ailments by 50%.",
    "Null Fear": "Protects user from Fear.",
    "Null Panic": "Protects user from Panic.",
    "Null Distress": "Protects user from Distress.",
    "Null Poison": "Protects user from Poison.",
    "Null Charm": "Protects user from being Charmed.",
    "Null Rage": "Protects user from becoming Enraged.",
    "Null Shock": "Protects user from being Shocked.",
    "Null Freeze": "Protects user from being Frozen.",
    "Auto-Tarukaja": "Automatic Tarukaja at the start of battle.",
    "Auto-Rakukaja": "Automatic Rakukaja at the start of battle.",
    "Auto-Sukukaja": "Automatic Sukukaja at the start of battle.",
    "Auto-Mataru ": "Automatic Matarukaja at the start of battle.",
    "Auto-Maraku": "Automatic Marakukaja at the start of battle.",
    "Auto-Masuku": "Automatic Masukukaja at the start of battle. ",
    "Divine Grace": "Greatly strengthens restorative magic by 100%",
    "Regenerate 1": "Restores 2% HP each turn in battle.",
    "Regenerate 2 ": "Restores 4% HP each turn in battle.",
    "Regenerate 3": "Restores 6% HP each turn in battle.",
    "Spring of Life": "Restores 8% HP each turn in battle.Trismegistus exclusive.",
    "Invigorate 1": "Restores 3 SP each turn in battle.",
    "Invigorate 2": "Restores 5 SP each turn in battle.",
    "Invigorate 3": "Restores 7 SP each turn in battle.",
    "Cool Breeze": "Restores 8% HP and SP after battle.",
    "Victory Cry": "Fully restores HP and SP after battle.",
    "Growth 1": "Persona gains 1/4 EXP while inactive.",
    "Growth 2": "Persona gains 1/2 EXP while inactive.",
    "Growth 3": "Persona gains full EXP while inactive.",
    "Endure": "Restores 1 HP upon death 1 time per battle.",
    "Enduring Soul": "Restores all HP upon death 1 time per battle.",
    "Counter": "Counter physical attacks (low odds). (15% chance)",
    "Counterstrike": "Counter physical attacks (med odds). (30% chance)",
    "High Counter": "Counter physical attacks (high odds). (50% chance)",
    "Alertness": "Lowers odds of being taken by surprise.",
    "Fast Retreat": "Increases chance of escape.",
    "Apt Pupil": "Increases user's Critical Rate.",
    "Sharp Student": "Lowers odds of sustaining critical damage.",
    "Raging Tiger": "Doubles attack power while Enraged.",
    "1hSwd Master*": "Doubles damage dealt by a 1-handed sword.",
    "2hSwd Master*": "Doubles damage dealt by a 2-handed sword.",
    "Fist Master*": "Doubles damage dealt by a fist weapon.",
    "Heavy Master*": "Doubles damage dealt by a bludgeon.",
    "Spear Master*": "Doubles damage dealt by a spear.",
    "Bow Master*": "Doubles damage dealt by a bow.",
    "Weapons Master": "Doubles damage dealt with weapons. (Portable only)",
    "Goddess Knowledge": "Doubles damage dealt by Slash, Strike, and Pierce attacks.\"???\" exclusive.\n\n",
    "Arms Master": "Halves HP cost for physical skills.",
    "Spell Master": "Halves SP cost for magic skills.",
    "Unshaken Will": "Protects user from mental ailments.Asura exclusive.",
    "Magic Skill Up": "Strengthens all magical attacks, including Almighty, by 50%.Messiah exclusive (Portable only).",
    "Analysis": "Displays enemy information (stats and resistances).",
    "Full Analysis": "Displays detailed enemy information (stats, resistances, and skills).",
    "Support Scan": "Displays all buffs and debuffs currently in effect.",
    "Third Eye": "Increases information displayed on the target(shows whether an attack will be nulled, repelled, or absorbed).",
    "Healing Wave": "Party recovers 15% HP when ascending to the next floor.",
    "Oracle": "Causes one of the following effects:1. HP restored. 2. SP restored. 3. HP and SP restored.4. All status ailments cured. 5. HP and SP reduced to 1.",
    "Escape Route": "Return to the entrance of Tartarus or the Desert of Doors.",
    "Cadenza": "Restores 50% HP / Evasion up (party).",
    "Justice": "Halves all foes' HP via Light magic.",
    "Jack Brothers": "Knocks down all foes (med odds).",
    "Frolic": "Fully restores party's HP but may inflict Charm (low chance).",
    "King and I": "Deals medium Ice damage/Freezes all foes (moderate chance).",
    "Dreamfest": "Inflicts Charm on all foes (high odds).",
    "Summer Dream": "One of the following happens at random:\n\nFully restores the party's HP and SP.\nFully restores all foe's HP and SP.\nFully restores everyone's HP and SP.\nKnocks down all allies.\nKnocks down all foes.\nKnocks down everyone.\nEveryone suffers a random ailment.\nNothing.\n\n",
    "Best Friends": "Combines all -kaja skills on one ally.",
    "Thunder Call": "Deals heavy Elec damage/Shocks all foes (high chance).",
    "Valhalla": "Grants one ally invincibility for 1 turn butdrops HP and SP to 1 after the effect fades",
    "Scarlet Havoc": "Deals heavy Slash damage to all foes.",
    "Shadow Hound": "Deals heavy Strike damage to all foes.",
    "Raktapaksha": "Knocks Down all foes (med odds) and casts Dekaja.",
    "Trickster": "Inflicts random ailments on all foes (high chance).",
    "Infinity": "Invulnerability for 1 turn (party).",
    "Ardhanari": "Deals massive Fire damage to all foes.",
    "Last Judge": "Deals severe Almighty damage to all foes.",
    "Armageddon": "Deals ultimate damage to all foes (9999)."
}